# Site settings
name: Kevin deLeon
email: kevin.deleon@gmail.com
title: "Kevin deLeon | Web Design and Development | New Orleans, LA"
description: "The website and blog of Kevin deLeon -- front-end and back-end developer, currently residing in the swamp."
baseurl: ""
url: "http://kevin-deleon.com"
permalink: /:year/:month/:title
paginate: 10
paginate_path: /blog/page/:num
twitter_username: kevindeleon
github_username:  kevindeleon

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      is_post: true # automatically set is_post=true for all posts

# Sitemap settings
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
       # - "/index.html"
        - "/blog/index.markdown"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-sitemap
